extends OptionButton
func _ready():
	self.add_item("Level 1")
	self.add_item("Level 2")
	self.add_item("Level 3")
	self.add_item("Level 4")
	self.add_item("Level 5")
	self.add_item("Level 6")
	self.add_item("Level 7")
	self.add_item("Level 8")
